version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfiles/backend.Dockerfile
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./:/workspace

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/dockerfiles/frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: incident
      POSTGRES_PASSWORD: incident
      POSTGRES_DB: incident_intel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow

  prefect-server:
    image: prefecthq/prefect:2-python3.11
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"

  trainer:
    build:
      context: .
      dockerfile: docker/dockerfiles/worker.Dockerfile
    env_file:
      - .env.example
    depends_on:
      - mlflow
      - prefect-server
    profiles: ["mlops"]

  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  pgdata:
  mlflow-data:
